spring.config.import=optional:file:.env[.properties],optional:file:mcsv-notificacion/.env[.properties]
spring.application.name=mcsv-notificacion

server.port=${PORT}
services.usuario.url=${USUARIO_API_URL}

# PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion del servidor SMTP de Brevo
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${BREVO_SMTP_USERNAME}
spring.mail.password=${BREVO_SMTP_KEY}

# Propiedades obligatorias para la seguridad de la conexion
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Tu correo verificado
app.lavaclean.correo.remitente=${MAIL_FROM}

# Apache Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

spring.kafka.consumer.group-id=mcsv-notificacion
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties[spring.json.value.default.type]=mcsv.mcsv_notificacion.infrastructure.messaging.PedidoEstadoCambiadoEvent
spring.kafka.consumer.properties[spring.json.trusted.packages]=mcsv.mcsv_notificacion.infrastructure.messaging

app.kafka.topic.pedido-estado=pedido-estado-cambiado